/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.Vector;
import vista.nivel1.JFN1Juego1;
import vista.nivel2.JFN2Juego1;
import vista.nivel3.JFN3Juego1;
import vista.nivel4.JFN4Juego1;

/**
 *
 * @author carlo
 */
public class JFNiveles extends javax.swing.JFrame {
    Vector data = null;
    String sigueinteNivel;

    /**
     * Creates new form JFNiveles
     */
    public JFNiveles(String siguienteNivel, Vector data) {
        this.data=data;
        initComponents();

        //Validar Combo
        this.sigueinteNivel = siguienteNivel;
        bloquearBotones();
        switch (this.sigueinteNivel) {
            case "Nivel1":
                this.btnNivel1.setEnabled(true);
                break;
            case "Nivel2":
                this.btnNivel2.setEnabled(true);
                break;
            case "Nivel3":
                this.btnNivel3.setEnabled(true);
                break;
            case "Nivel4":
                this.btnNivel4.setEnabled(true);
                break;
            case "Resultados":
                this.btnResultados.setEnabled(true);
                break;
            default:
                this.btnNivel1.setEnabled(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNivel1 = new javax.swing.JButton();
        btnNivel2 = new javax.swing.JButton();
        btnNivel3 = new javax.swing.JButton();
        btnNivel4 = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Niveles");

        btnNivel1.setText("Nivel 1");
        btnNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel1ActionPerformed(evt);
            }
        });

        btnNivel2.setText("Nivel 2");
        btnNivel2.setEnabled(false);
        btnNivel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel2ActionPerformed(evt);
            }
        });

        btnNivel3.setText("Nivel 3");
        btnNivel3.setEnabled(false);
        btnNivel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel3ActionPerformed(evt);
            }
        });

        btnNivel4.setText("Nivel 4");
        btnNivel4.setEnabled(false);
        btnNivel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivel4ActionPerformed(evt);
            }
        });

        btnResultados.setText("Ver Resultados");
        btnResultados.setEnabled(false);
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNivel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNivel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNivel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNivel4))
                    .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNivel1)
                    .addComponent(btnNivel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNivel3)
                    .addComponent(btnNivel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResultados)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel1ActionPerformed
        // TODO add your handling code here:
        JFN1Juego1 oFN1Juego1 = new JFN1Juego1(data);
        oFN1Juego1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNivel1ActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
        JFResultados oJFResultados = new JFResultados(this.data);
        oJFResultados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnNivel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel2ActionPerformed
        // TODO add your handling code here:
        JFN2Juego1 oFN2Juego1 = new JFN2Juego1(data);
        oFN2Juego1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNivel2ActionPerformed

    private void btnNivel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel3ActionPerformed
        // TODO add your handling code here:
        JFN3Juego1 oFN3Juego1 = new JFN3Juego1(data);
        oFN3Juego1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNivel3ActionPerformed

    private void btnNivel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivel4ActionPerformed
        // TODO add your handling code here:
        JFN4Juego1 oFN4Juego1 = new JFN4Juego1(data);
        oFN4Juego1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNivel4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFNiveles("siguienteNivel",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNivel1;
    private javax.swing.JButton btnNivel2;
    private javax.swing.JButton btnNivel3;
    private javax.swing.JButton btnNivel4;
    private javax.swing.JButton btnResultados;
    // End of variables declaration//GEN-END:variables

    private void bloquearBotones() {
        this.btnNivel1.setEnabled(false);
        this.btnNivel2.setEnabled(false);
        this.btnNivel3.setEnabled(false);
        this.btnNivel4.setEnabled(false);
        this.btnResultados.setEnabled(false);
    }
}
