// default package
// Generated 28/01/2016 08:03:29 PM by Hibernate Tools 3.4.0.CR1

/**
 * LibroAutor generated by hbm2java
 */
public class LibroAutor implements java.io.Serializable {

	private LibroAutorId id;

	public LibroAutor() {
	}

	public LibroAutor(LibroAutorId id) {
		this.id = id;
	}

	public LibroAutorId getId() {
		return this.id;
	}

	public void setId(LibroAutorId id) {
		this.id = id;
	}

}
