// default package
// Generated 28/01/2016 08:03:29 PM by Hibernate Tools 3.4.0.CR1

/**
 * LibroAutorId generated by hbm2java
 */
public class LibroAutorId implements java.io.Serializable {

	private int idLibro;
	private int idAutor;

	public LibroAutorId() {
	}

	public LibroAutorId(int idLibro, int idAutor) {
		this.idLibro = idLibro;
		this.idAutor = idAutor;
	}

	public int getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(int idLibro) {
		this.idLibro = idLibro;
	}

	public int getIdAutor() {
		return this.idAutor;
	}

	public void setIdAutor(int idAutor) {
		this.idAutor = idAutor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LibroAutorId))
			return false;
		LibroAutorId castOther = (LibroAutorId) other;

		return (this.getIdLibro() == castOther.getIdLibro()) && (this.getIdAutor() == castOther.getIdAutor());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdLibro();
		result = 37 * result + this.getIdAutor();
		return result;
	}

}
